<?php

$username='516015a8-8572-4af3-b27f-ff1dc0752ba9';
$password='cdInhqJTKIyL';
$URL='https://gateway.watsonplatform.net/conversation/api/v1/workspaces?version=2017-02-03';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$URL);
curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
$result=curl_exec ($ch);

$data= json_decode($result);
echo '<pre>';
print_r($data);

echo '</pre>';

echo $status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);   //get status code
curl_close ($ch);


?>



<?php

$username='516015a8-8572-4af3-b27f-ff1dc0752ba9';
$password='cdInhqJTKIyL';
$URL='https://gateway.watsonplatform.net/conversation/api/v1/workspaces/25dfa8a0-0263-471b-8980-317e68c30488/message?version=2017-02-03';

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,$URL);
//curl_setopt($ch, CURLOPT_URL, "—-header");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"input\": {\"text\": \"Turn on the lights\"}, \"context\": {\"conversation_id\": \"1b7b67c0-90ed-45dc-8508-9488bc483d5b\", \"system\": {dialog_stack\":[{\"dialog_node\":\"root\"}],");
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_USERPWD, "$username" . ":" . "\"{password}\"");
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");

$headers = array();
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

?>


