<?php
session_start();
echo $username=$_SESSION['login'];
echo "<br>";
echo $password=$_SESSION['access_token'];
//$url='https://api.github.com/user/repos';
/*
$url='https://api.github.com/repos/gyana2014/testgit1';
$ch = curl_init($url);
//$post_args = array("name"=>  "testgit1" ); 
$imagedata = file_get_contents("error_log.txt");
$base64 = base64_encode($imagedata);
$post_args = array(
"name"=>  "testgitrwer",
 "content"=> $base64,
  "encoding"=> "utf-8"
); 
$dataen = json_encode($post_args);
curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:7.0.1) Gecko/20100101 Firefox/7.0.1');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS,  $dataen);
curl_setopt($ch, CURLOPT_TIMEOUT, 30); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, $username.':'.$password);
$status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);   //get status code
$result=curl_exec ($ch);
if(curl_exec($ch) === false)
{
    echo 'Curl error: ' . curl_error($ch);
}

curl_close ($ch);
$array=json_decode($result);
echo "<pre>";
print_r($array);
echo "</pre>";*/
echo "=================================================";
?>
<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$ch1 = curl_init();
$imagedata = file_get_contents("error_log.txt");
$base64 = base64_encode($imagedata);
$arrtyyy=array(//"path"=>"gyan/error_log.txt",
		"message"=>"Initial Commist",
		"committer"=>array("name"=>$username,
		"email"=>"naveen.pateriya@adynor.com"),"content"=>$base64,
		//"sha" =>"1c68e684f232a1357dc502cd458bd1af0622044e"
		"sha" => "51b9912d4c4fe765d20a90ddd0bc44e1b1b3f971"
		);
		$url="https://api.github.com/repos/naveen0/testgit56/contents/error_log2.txt";
	//$url="https://api.github.com/repos/gyana2014/testgit/git/blobs/51b9912d4c4fe765d20a90ddd0bc44e1b1b3f971";	
 curl_setopt($ch1,CURLOPT_USERAGENT,'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:7.0.1) Gecko/20100101 Firefox/7.0.1');
 
curl_setopt($ch1, CURLOPT_URL, $url );

curl_setopt($ch1, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, "PUT");
curl_setopt($ch1, CURLOPT_POSTFIELDS, json_encode($arrtyyy));


$headers1 = array();
$headers1[] = 'Authorization: token ' . $_SESSION['access_token'];
$headers1[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch1, CURLOPT_HTTPHEADER, $headers1);

$result1 = curl_exec($ch1);
if (curl_errno($ch1)) {
    echo 'Error:' . curl_error($ch1);
}
curl_close ($ch1);
$array1=json_decode($result1);
echo "<pre>";
print_r($array1);
echo "</pre>";
?>